version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - ${RABBIT_PORT:-5672}:5672
      - ${RABBIT_PORT:-15672}:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  storage:
    image: openzipkin/zipkin-mysql
    container_name: zipkin-mysql
    ports:
      - 3306:3306
    volumes:
      - dbfiles:/mysql/data
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3306"]
        interval: 30s
        timeout: 10s
        retries: 5

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: on-failure
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-mysql
    ports:
      - ${ZIPKIN_PORT:-9411}:9411
    depends_on:
      - rabbitmq
      - storage
    links:
      - rabbitmq
      - storage

volumes:
  dbfiles: