version: '3'

services:
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: zipkin
    container_name: zipkin
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672
      # Set storage type
      - STORAGE_TYPE=elasticsearch
      # Point the zipkin at the storage backend
      - ES_HOSTS=elasticsearch
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - ${ZIPKIN_PORT:-9411}:9411
    depends_on:
      - rabbitmq
      - storage
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine
    container_name: rabbitmq
    ports:
      - ${RABBIT_PORT:-5672}:5672
      - ${RABBIT_PORT:-15672}:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  storage:
    image: openzipkin/zipkin-elasticsearch6
    container_name: elasticsearch
    # Expose the storage port for testing
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - dbfiles:/elasticsearch/data
    # Uncomment to restart if it get down
    # restart: unless-stopped

volumes:
  dbfiles: